import { Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "./_lib/QueryProvider";

const inter = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-pop",
  display: "swap",
});

export const metadata = {
  title: "HealHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
